//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD.WinForms.PDServiceReferenceASMX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneDictionaryModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PhoneDictionaryModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNum {
            get {
                return this.PhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumField, value) != true)) {
                    this.PhoneNumField = value;
                    this.RaisePropertyChanged("PhoneNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PDServiceReferenceASMX.PDServiceSoap")]
    public interface PDServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем HelloWorldResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        PD.WinForms.PDServiceReferenceASMX.HelloWorldResponse HelloWorld(PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.HelloWorldResponse> HelloWorldAsync(PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetAllResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        PD.WinForms.PDServiceReferenceASMX.GetAllResponse GetAll(PD.WinForms.PDServiceReferenceASMX.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.GetAllResponse> GetAllAsync(PD.WinForms.PDServiceReferenceASMX.GetAllRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        PD.WinForms.PDServiceReferenceASMX.GetResponse Get(PD.WinForms.PDServiceReferenceASMX.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.GetResponse> GetAsync(PD.WinForms.PDServiceReferenceASMX.GetRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем value из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        PD.WinForms.PDServiceReferenceASMX.PostResponse Post(PD.WinForms.PDServiceReferenceASMX.PostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.PostResponse> PostAsync(PD.WinForms.PDServiceReferenceASMX.PostRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем value из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Put", ReplyAction="*")]
        PD.WinForms.PDServiceReferenceASMX.PutResponse Put(PD.WinForms.PDServiceReferenceASMX.PutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Put", ReplyAction="*")]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.PutResponse> PutAsync(PD.WinForms.PDServiceReferenceASMX.PutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PD.WinForms.PDServiceReferenceASMX.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PD.WinForms.PDServiceReferenceASMX.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(PD.WinForms.PDServiceReferenceASMX.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(PD.WinForms.PDServiceReferenceASMX.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(PD.WinForms.PDServiceReferenceASMX.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(PD.WinForms.PDServiceReferenceASMX.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PostRequestBody Body;
        
        public PostRequest() {
        }
        
        public PostRequest(PD.WinForms.PDServiceReferenceASMX.PostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value;
        
        public PostRequestBody() {
        }
        
        public PostRequestBody(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostResponse", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PostResponseBody Body;
        
        public PostResponse() {
        }
        
        public PostResponse(PD.WinForms.PDServiceReferenceASMX.PostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostResponseBody {
        
        public PostResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Put", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PutRequestBody Body;
        
        public PutRequest() {
        }
        
        public PutRequest(PD.WinForms.PDServiceReferenceASMX.PutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value;
        
        public PutRequestBody() {
        }
        
        public PutRequestBody(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutResponse", Namespace="http://tempuri.org/", Order=0)]
        public PD.WinForms.PDServiceReferenceASMX.PutResponseBody Body;
        
        public PutResponse() {
        }
        
        public PutResponse(PD.WinForms.PDServiceReferenceASMX.PutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutResponseBody {
        
        public PutResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PDServiceSoapChannel : PD.WinForms.PDServiceReferenceASMX.PDServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PDServiceSoapClient : System.ServiceModel.ClientBase<PD.WinForms.PDServiceReferenceASMX.PDServiceSoap>, PD.WinForms.PDServiceReferenceASMX.PDServiceSoap {
        
        public PDServiceSoapClient() {
        }
        
        public PDServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PDServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PD.WinForms.PDServiceReferenceASMX.HelloWorldResponse PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.HelloWorld(PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest inValue = new PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.HelloWorldRequestBody();
            PD.WinForms.PDServiceReferenceASMX.HelloWorldResponse retVal = ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.HelloWorldResponse> PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.HelloWorldAsync(PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.HelloWorldResponse> HelloWorldAsync() {
            PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest inValue = new PD.WinForms.PDServiceReferenceASMX.HelloWorldRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.HelloWorldRequestBody();
            return ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PD.WinForms.PDServiceReferenceASMX.GetAllResponse PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.GetAll(PD.WinForms.PDServiceReferenceASMX.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel[] GetAll() {
            PD.WinForms.PDServiceReferenceASMX.GetAllRequest inValue = new PD.WinForms.PDServiceReferenceASMX.GetAllRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.GetAllRequestBody();
            PD.WinForms.PDServiceReferenceASMX.GetAllResponse retVal = ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.GetAllResponse> PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.GetAllAsync(PD.WinForms.PDServiceReferenceASMX.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.GetAllResponse> GetAllAsync() {
            PD.WinForms.PDServiceReferenceASMX.GetAllRequest inValue = new PD.WinForms.PDServiceReferenceASMX.GetAllRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.GetAllRequestBody();
            return ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PD.WinForms.PDServiceReferenceASMX.GetResponse PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.Get(PD.WinForms.PDServiceReferenceASMX.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel Get(System.Guid id) {
            PD.WinForms.PDServiceReferenceASMX.GetRequest inValue = new PD.WinForms.PDServiceReferenceASMX.GetRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.GetRequestBody();
            inValue.Body.id = id;
            PD.WinForms.PDServiceReferenceASMX.GetResponse retVal = ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.GetResponse> PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.GetAsync(PD.WinForms.PDServiceReferenceASMX.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.GetResponse> GetAsync(System.Guid id) {
            PD.WinForms.PDServiceReferenceASMX.GetRequest inValue = new PD.WinForms.PDServiceReferenceASMX.GetRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.GetRequestBody();
            inValue.Body.id = id;
            return ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PD.WinForms.PDServiceReferenceASMX.PostResponse PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.Post(PD.WinForms.PDServiceReferenceASMX.PostRequest request) {
            return base.Channel.Post(request);
        }
        
        public void Post(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value) {
            PD.WinForms.PDServiceReferenceASMX.PostRequest inValue = new PD.WinForms.PDServiceReferenceASMX.PostRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.PostRequestBody();
            inValue.Body.value = value;
            PD.WinForms.PDServiceReferenceASMX.PostResponse retVal = ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).Post(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.PostResponse> PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.PostAsync(PD.WinForms.PDServiceReferenceASMX.PostRequest request) {
            return base.Channel.PostAsync(request);
        }
        
        public System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.PostResponse> PostAsync(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value) {
            PD.WinForms.PDServiceReferenceASMX.PostRequest inValue = new PD.WinForms.PDServiceReferenceASMX.PostRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.PostRequestBody();
            inValue.Body.value = value;
            return ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).PostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PD.WinForms.PDServiceReferenceASMX.PutResponse PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.Put(PD.WinForms.PDServiceReferenceASMX.PutRequest request) {
            return base.Channel.Put(request);
        }
        
        public void Put(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value) {
            PD.WinForms.PDServiceReferenceASMX.PutRequest inValue = new PD.WinForms.PDServiceReferenceASMX.PutRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.PutRequestBody();
            inValue.Body.value = value;
            PD.WinForms.PDServiceReferenceASMX.PutResponse retVal = ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).Put(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.PutResponse> PD.WinForms.PDServiceReferenceASMX.PDServiceSoap.PutAsync(PD.WinForms.PDServiceReferenceASMX.PutRequest request) {
            return base.Channel.PutAsync(request);
        }
        
        public System.Threading.Tasks.Task<PD.WinForms.PDServiceReferenceASMX.PutResponse> PutAsync(PD.WinForms.PDServiceReferenceASMX.PhoneDictionaryModel value) {
            PD.WinForms.PDServiceReferenceASMX.PutRequest inValue = new PD.WinForms.PDServiceReferenceASMX.PutRequest();
            inValue.Body = new PD.WinForms.PDServiceReferenceASMX.PutRequestBody();
            inValue.Body.value = value;
            return ((PD.WinForms.PDServiceReferenceASMX.PDServiceSoap)(this)).PutAsync(inValue);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
