//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD.WinForms.PDServiceReferenceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PDServiceReferenceWCF.IPDService")]
    public interface IPDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/GetAll", ReplyAction="http://tempuri.org/IPDService/GetAllResponse")]
        PD.DataCore.Models.PhoneDictionaryModel[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/GetAll", ReplyAction="http://tempuri.org/IPDService/GetAllResponse")]
        System.Threading.Tasks.Task<PD.DataCore.Models.PhoneDictionaryModel[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Get", ReplyAction="http://tempuri.org/IPDService/GetResponse")]
        PD.DataCore.Models.PhoneDictionaryModel Get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Get", ReplyAction="http://tempuri.org/IPDService/GetResponse")]
        System.Threading.Tasks.Task<PD.DataCore.Models.PhoneDictionaryModel> GetAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Add", ReplyAction="http://tempuri.org/IPDService/AddResponse")]
        void Add(PD.DataCore.Models.PhoneDictionaryModel value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Add", ReplyAction="http://tempuri.org/IPDService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(PD.DataCore.Models.PhoneDictionaryModel value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Update", ReplyAction="http://tempuri.org/IPDService/UpdateResponse")]
        void Update(PD.DataCore.Models.PhoneDictionaryModel value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Update", ReplyAction="http://tempuri.org/IPDService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(PD.DataCore.Models.PhoneDictionaryModel value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Delete", ReplyAction="http://tempuri.org/IPDService/DeleteResponse")]
        void Delete(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPDService/Delete", ReplyAction="http://tempuri.org/IPDService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPDServiceChannel : PD.WinForms.PDServiceReferenceWCF.IPDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PDServiceClient : System.ServiceModel.ClientBase<PD.WinForms.PDServiceReferenceWCF.IPDService>, PD.WinForms.PDServiceReferenceWCF.IPDService {
        
        public PDServiceClient() {
        }
        
        public PDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PD.DataCore.Models.PhoneDictionaryModel[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PD.DataCore.Models.PhoneDictionaryModel[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PD.DataCore.Models.PhoneDictionaryModel Get(System.Guid id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<PD.DataCore.Models.PhoneDictionaryModel> GetAsync(System.Guid id) {
            return base.Channel.GetAsync(id);
        }
        
        public void Add(PD.DataCore.Models.PhoneDictionaryModel value) {
            base.Channel.Add(value);
        }
        
        public System.Threading.Tasks.Task AddAsync(PD.DataCore.Models.PhoneDictionaryModel value) {
            return base.Channel.AddAsync(value);
        }
        
        public void Update(PD.DataCore.Models.PhoneDictionaryModel value) {
            base.Channel.Update(value);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(PD.DataCore.Models.PhoneDictionaryModel value) {
            return base.Channel.UpdateAsync(value);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
